---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.kubesys.io
spec:
  additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      name: created
      type: string
  group: kubesys.io
  names:
    kind: Image
    plural: images
    singular: image
  scope: Namespaced
  version: v1