---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: userroles.kubesys.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: kubesys.io
  names:
    kind: UserRole
    plural: userroles
    singular: userrole
  scope: Namespaced
  version: v1
